
name: Basic Github Action
on: 
  workflow_dispatch:
jobs:
  Build:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v3.3.0
     - name: List files in the repository
       run: |
          echo "The job was triggered by event: ${{ github.event_name }}"
          echo "The name of branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
